Feature/migrate null safety
Danopie/lightweight_bloc pull request #1
Opened 2021-03-18 10:21 UTC by huynn109

- [ x] Tested
- [ x] Add example

2021-03-19 09:47 UTC, Danopie requested changes
A few places can be non-nullable for this library to be more robust and future-proof

2021-03-19 09:47 UTC, Danopie commented on pubspec.yaml
> +  test: ^1.16.5
Bỏ dependency này nha a mốt lại phải update nữa

2021-03-19 09:47 UTC, Danopie commented on lib/src/bloc.dart
> +  late List<T?> _previousStates;
previousStates có thể nonnull nè a

2021-03-19 09:47 UTC, Danopie commented on lib/src/bloc.dart
> +  T? _state;
state cũng vậy

2021-03-19 09:47 UTC, Danopie commented on lib/src/bloc.dart
> +  T? get state => _state;
non-null được luôn

2021-03-19 09:47 UTC, Danopie commented on lib/src/bloc_provider.dart
> +  final Widget? child;
child nên nonnull

2021-03-19 09:47 UTC, Danopie commented on lib/src/bloc_provider.dart
> +  final BlocBuilderFunction<T>? builder;
2 cái này nên non null

2021-03-19 09:47 UTC, Danopie commented on lib/src/bloc_observer.dart
Ở dây nên dùng dynamic thay vì Object và để non null

2021-08-20 01:21 UTC, closed without merging

2021-08-20 11:40 UTC, Danopie commented
a @huynn109 ơi đừng như thế =))

2021-08-20 13:57 UTC, huynn109 commented
Giận rồi 😂